title: Moyin Ajayi # your name (or website title) here
logo: "/images/linkedinPic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist with experience in machine learning, predictive analytics and artificial intelligence.
  I love building and deploying machine learning models, working with but structured and unstructured data and engineering features to strenghthen predictions
  I work with Python, SQL, PowerBI, Tableau and I am quite flexible to adapt to any related tools for data management
  
  <br><br>
  I am also a certified Azure data engineer with experience building data pipelines in Azure. 
  <br><br>

   <div class="about__skill-info">
            <h3 class="heading-quaternary about__heading-quaternary">
              My Skills
            </h3>
            <ul class="about__skills">
              <li class="about__skill">python</li>
              <li class="about__skill">sql</li>
              <li class="about__skill">java</li>
              <li class="about__skill">git</li>
              <li class="about__skill">vscode</li>
              <li class="about__skill">html</li>
              <li class="about__skill">javascript</li>
            </ul>
          </div>
          
  <a href="https://www.linkedin.com/in/moyinajayi/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
